server:
  port: 8082

springdoc:

  api-docs:
    path: /docs

  swagger-ui:
    filter: true
    tryItOutEnabled: true
    path: /swagger

spring:
  application:
    name: image-api

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/otus?useUnicode=true&characterEncoding=UTF8
    username: postgres
    password: postgres
  #  h2:
  #    console.enabled: true
  #    console:
  #      path: /h2-console
  #  datasource:
  #    url: jdbc:h2:mem:cooking
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  liquibase:
    change-log: classpath:liquibase/master.xml
    enabled: true

logging:
  level:
    ru.otus.example: DEBUG

upload:
  image-path:
    photo:  "C:\\temp\\photo"